Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,18 +46,10 @@ jobs:
 
   # Workflow block for building iOS
   build-ios:
-    runs-on: macos-latest
+    runs-on: macos-14
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: Set up latest Xcode
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: latest
-
-      - name: Check Xcode version
-        run: xcodebuild -version
 
       - name: Set up JDK
         uses: actions/setup-java@v4
@@ -65,14 +57,15 @@ jobs:
           java-version: '17'
           distribution: 'zulu'
 
-      - name: Install CocoaPods (if needed)
+      - name: Install Xcode Command Line Tools
         run: |
-          if [ -f iosApp/Podfile ]; then
-            echo "Installing CocoaPods dependencies..."
-            pod install --project-directory=iosApp
+          if ! xcode-select --print-path > /dev/null 2>&1; then
+            echo "Xcode Command Line Tools are not installed. Installing..."
+            xcode-select --install || echo "Failed to install Xcode Command Line Tools"
           else
-            echo "No Podfile found. Skipping CocoaPods installation."
+            echo "Xcode Command Line Tools are already installed"
           fi
+          
       - name: Build iOS app
         run: |
           if [ -d iosApp/iosApp.xcworkspace ]; then
@@ -98,12 +91,29 @@ jobs:
               CODE_SIGN_IDENTITY="" \
               DEVELOPMENT_TEAM=""
           fi
-      - name: Upload iOS build artifacts
+      - name: List Xcode build products
+        run: |
+          echo "Listing contents of the DerivedData directory:"
+          ls -R ~/Library/Developer/Xcode/DerivedData
+      - name: Find the latest .app file
+        id: find-app
+        run: |
+          # Find all .app directories and sort them by modification time
+          LATEST_APP=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" -type d -print0 | xargs -0 stat -f "%m %N" | sort -nr | head -n 1 | cut -d ' ' -f 2-)
+          if [ -z "$LATEST_APP" ]; then
+            echo "Error: No .app file found!"
+            exit 1
+          fi
+          echo "Found latest .app file at $LATEST_APP"
+          echo "LATEST_APP=$LATEST_APP" >> $GITHUB_ENV
+      - name: Archive iOS app
+        run: |
+          cp -R "$LATEST_APP" .
+      - name: Upload iOS app
         uses: actions/upload-artifact@v4
         with:
-          name: ios-build-artifacts
-          path: |
-            iosApp/build/Release-iphoneos/*.app
+          name: ios-app
+          path: "*.app"
 
   # Workflow block for building Desktop
   build-desktop:
@@ -134,7 +144,28 @@ jobs:
           name: desktop-jar
           path: composeApp/build/libs/*.jar
 
-  # Workflow block for building msi
+  # Workflow block for building macOS
+  build-macos:
+    runs-on: macos-14
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install Dependencies
+        run: brew install create-dmg
+
+      - name: Build macOS app
+        run: |
+          xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -scheme iosApp -configuration Release -sdk iphoneos -destination name='iPhone 14' build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM=""
+      - name: Create DMG
+        run: |
+          ./gradlew packageDmg
+      - name: Upload DMG
+        uses: actions/upload-artifact@v4
+        with:
+          name: macos-dmg
+          path: composeApp/build/compose/binaries/main/dmg/*.dmg
+
   build-msi:
     runs-on: macos-14
     steps:
@@ -194,7 +225,7 @@ jobs:
   # Workflow block for generating artifact links
   generate-artifact-links:
     runs-on: ubuntu-latest
-    needs: [ build-android, build-ios, build-desktop, build-msi, build-web ]
+    needs: [ build-android, build-ios, build-desktop,build-macos, build-msi, build-web ]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
